### PR TITLE
Add GitHub Actions workflow

### PR DESCRIPTION
**Pull request by zmughal**
Example run: <https://github.com/zmughal/extutils-cppguess/runs/2713446703?check_suite_focus=true>

### CODE REVIEW

**Comment by zmughal** [comment]
Ready for review:

- workflow run: <https://github.com/zmughal/extutils-cppguess/actions/runs/894058532>
- coverage report: <https://coveralls.io/jobs/81158436>

**Comment by mohawk2** [comment]
Thanks!

**Comment by mohawk2** [comment]
As a stretch goal, any chance of a Win32 as well? :-D

**Comment by mohawk2** [comment]
Sorry, just noticed in build for #22 that there already is one!

**Pull request merged**
